module.exports = [
    {
     "menu_name": "Dinner",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Dinner",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Appetizers",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Drinks",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "2"
    },
    {
     "menu_name": "Lunch",
     "subgroup_name": "Entree",
     "subgroup_desc": "add cheese for $1.00",
     "entry_name": "artichoke",
     "entry_desc": "tasty",
     "entry_price": "$27.00",
     "extras_name": "ranch",
     "extras_price": "$0.50",
     "restaurant_id": "1"
    }
   ]